### PR TITLE
Add Dockerfiles and docker-compose file

### PR DESCRIPTION
**Pull request by vfreex**
so that you can run TeamTalk-NG in containers!

### CODE REVIEW

**Comment by shiywang** [comment]
I guess we should merge https://github.com/teamtalk-remix/teamtalk-ng/pull/1 before merging this ?

**Comment by vfreex** [comment]
> I guess we should merge #1 before merging this ?

Without #1, the Dockerfile doesn't work.

**Comment by vfreex** [comment]
Rebased

**Pull request merged**
